config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'home/databaseInfo', to:"home#databaseInfo"
  get 'home/mailInfo', to:"home#mailInfo"
  get 'home/sequencer', to:"home#sequencer"


  root 'home#index'

  resources :members
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def databaseInfo
  end

  def mailInfo
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!

  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :age, :intrest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/index.html.erb
<div class="container">
<p class="alert"><%= alert %></p>

  <h3>Welcome</h3>
<div class="card">
  <div class="card-body">
   <p>You are visiting the Good Works On Earth research site containing our database designed to research English in a revealing way. To share with you some of the earlier results of this long research ..</p>
<p>We Invite You ..<p>
<p>Enjoy instant access to our free ebook, entitled ..<p>

<h3>StarLight Expressions of the Letters Trestle
            by, Kathy Onu</h3>

      <% if current_user %>   
        <a href="app\assets\stararts.pdf" download class="btn btn-outline-success" >  
      StarLight Expressions
  </a> <% else %>
  <%= link_to "login", new_user_session_path, class:"btn btn-outline-info" %>

      <% end %>    

      <p class="mt-4">You can save this ebook ~ or ~
You can view in Preview, or other suitable .pdf format readers.</p>

<p>This book is about the Star Arts of English words that are created using the art and science of the *Lexigram.</p>

<p>All seekers of truth visiting Good Works On Earth's site are immediately and always able to download this ebook as our Thank You to you for your caring to awaken and heal thysElf.</p>

<p>Please accept our ebook, a gift to every human on earth in the name of awakenings and healings, in plain English.</p>

<b>* Lexigram</b>, comes from two word parts:

<b>lexi</b> : means, the word.
An example is lexicon, meaning the word reference, the dictionary.

<b>-gram</b> : a suffix, meaning .. drawn out in full or written out in full.

<b>Lexigram</b>, as a word, and as an art and a science, is shared with Star Arts examples, in this free ebook.

  </div>
</div>
<p>
</div>

<!--<%= link_to "register", new_user_registration_path%>
<%= link_to "login", new_user_session_path %>
   <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% if current_user %>   
        <%= current_user.email %>
        <%= button_to "log out", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn btn-success" %>
      <% end %> -->
 

app/views/home/mailInfo.html.erb
<h1>all mail</h1>

app/views/home/sequencer.html.erb
<div class="container mt-4">
<p>This application was developed to take any text entry and sequence it, generating its various sequences of creation, and relating those sequences to their English creations in words, phrases, names, and new creations.</p>
    <div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Site Description
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
<p>Please accept our offer of the free ebook,</p>
<%= link_to  home_index_path, class:"badge rounded-pill bg-success" do%>StarLight Express ~ The Letter's Trestle.
<% end %>


From your seeing that, the following will make sense.

Ours is a desktop application. While you can enjoy the site on your small screen, you cannot access the database capablilties on a small screen, it simply will not serve the information in an aligned and easly readable manner. Our codes are capable of sequencing the entire English language, from any time period, including new creations. The Sequencers database enables us to relate the letter sequences to their creations. Similar to the Genome Project's decoding of the DNA, here we also use letters and words to show relationships of creation. Our DNA uses four letters. English uses twenty-six letters.

Particular results the researchers seek are contained in the particular sequence searches.      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Developments
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
<p>Members can see and now prove and so know words really do lead to their
actions in reactions or creations.</p>

<p>This work is dedicated to Peace On Earth Good Will All.</p>

Words are key, and kindness counts, we are all kin.

Kind Kin In I In Kindness.      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Membership Info
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
Member's usages guide further development of Sequencers.

Members enjoy the benefits as further developed.

The benefits now are substantial, if you Love English      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        Webmaster
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
<p>Sequencers is built by Kathy Onu for</p>
<a href="http://www.goodworksonearth.org/">http://www.goodworksonearth.org/</a>

<p>Contact the webmaster</p>      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Membership</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

      <!--<p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% if current_user %>   
        <%= current_user.email %>
        <%= button_to "log out", destroy_user_session_path, method: :delete, data: {turbo: false} %>
      <% end %>  --> 
      <%# nav bar %>
<%= render partial: 'shared/navBar' %>
      <%= yield %>
     <div class="footer pt-2">
  <p>Sequencers Services are provided by Good Works On Earth</br>
  a 501(c)3 charitable and educational non-profit organization</p>
</div>

  </body>

  <style>
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: pink;
   color: white;
   text-align: center;
   margin-top: auto;
    font-size: 10px; 
}
body{
    min-height: 200vh;
    display: flex;
    flex-direction: column;
}
</style>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :intrest, style: "display: block" %>
    <%= form.text_field :intrest %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= member.age %>
  </p>

  <p>
    <strong>Intrest:</strong>
    <%= member.intrest %>
  </p>

</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>



<h1>Members</h1>

<div id="members">
  <% @members.each do |member| %>
    <%= render member %>
    <p>
      <%= link_to "Show this member", member %>
    </p>
  <% end %>
</div>

<%= link_to "New member", new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", @member, method: :delete %>
</div>

app/views/shared/_navBar.html.erb
<nav class="navbar navbar-expand-lg  " style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <%= link_to "Sequencers Membership", new_user_session_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Hello Visitor", home_index_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Database Info", home_databaseInfo_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "MailList Info", home_index_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Sequencers", home_sequencer_path, class:"nav-link" %>
        </li>
      </ul>
      <div class="d-flex" role="search">
        <%# <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button> %>
        <% if current_user %>   
          <!--<%= current_user.email %>-->
          <%= button_to "log out", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn btn-success" %>
        <% else %>
          <%= link_to "login", new_user_session_path, class: "btn btn-outline-info"  %>
        <% end %> 
      </div>
     
    </div>
  </div>
</nav>